### ISSUE TITLE
Como cadastrar códigos de desconto para eventos?

### ISSUE THREAD

**Issue by rafaeleyng** [CWISoftware/eventos#12]
A CWI consegue, em alguns eventos, códigos promocionais de desconto.

Esses códigos devem ser acessíveis aos funcionários, mas não deveriam ser acessíveis ao público externo.

Como resolver isso? Não queria colocar autenticação no site de eventos.

**Comment by evertonz23** [comment]
O usuário com interesse no cupom de desconto, poderia informar o seu email, assim o sistema enviaria o código para o mesmo. Obviamente somente emails *@.cwi.com.br

**Comment by Alexandre-Machado** [comment]
Ainda teria que esconder a base de dados para os códigos não ficarem no git, visto que hoje ela é pública. #goodquestion

**Comment by johnvoloski** [comment]
Sendo público, não teria uma maneira segura de compartilhar isso, pois a lógica ficaria no fonte. Só se dependesse de algum tipo de autenticação externa. A softwareexpress possui um serviço de compartilhamento de arquivos, podiamos ter algo baseado em autenticação via ad, que gerasse um link externo pra acesso/download.

**Comment by rafaeleyng** [comment]
@Alexandre-Machado @johnvoloski isso, dadas as constraints desse site de eventos, teria que ser alguma solução criativa e que fosse algo simples de manter.

Qualquer ideia é bem-vinda :+1:

**Comment by johnvoloski** [comment]
@rafaeleyng , podiamos criptografar com algum algoritmo que precise de alguma chave privada, assim o colaborador solicita ao rh por email, e no próprio site coloca a chave e será exibido o valor correto.

**Comment by Alexandre-Machado** [comment]
Ou podíamos usar um site SharePoint que já tem área para documentos e integração com o AD. Ai o cara poe o link para o arquivo com o código. Colocamos o grupo de usuários CWI com acesso full ou só leitura.

**Comment by johnvoloski** [comment]
:+1: bem melhor.

**Comment by rafaeleyng** [comment]
@Alexandre-Machado acho que é por aí :+1: 

Quem e como faria a atualização dos cupons de desconto?
