### ISSUE TITLE
Aplicar filtro de pesquisa para diferentes tipos de eventos

### ISSUE THREAD

**Issue by alexandrepalagem** [CWISoftware/eventos#21]
Junto com a pesquisa poderia ser possível filtrar também por tipos de eventos como: Internos, Externos e CWI nos eventos.

**Comment by alexandrepalagem** [comment]
Adicionei os elementos para o filtro no PR https://github.com/CWISoftware/eventos/pull/24

![image](https://cloud.githubusercontent.com/assets/5439929/11156007/45b0f5c2-8a30-11e5-920b-68b3085e6e45.png)

**Comment by rafaeleyng** [comment]
Resolvido no #24
