### ISSUE TITLE
Possibilitar não visualizar eventos já passados

### ISSUE THREAD

**Issue by brunotrassante** [CWISoftware/eventos#22]

**Comment by rafaeleyng** [comment]
Como o volume de eventos não é muito grande, acho que em vez de ocultar, poderíamos estilizar os eventos já passados de forma diferente, meio esmaecido, ou com algum ícone que represente que já eras.

**Comment by rafaeleyng** [comment]
Resolvido no 2c7848e60bd8af5dbd10711d3ffea186ea4f855e
