### ISSUE TITLE
Juntar os grupo Externo e Interno em um "Todos"

### ISSUE THREAD

**Issue by brunotrassante** [CWISoftware/eventos#28]
Sugiro que criemos uma categoria todos, que seria a default, para ver misturados os internos e externos, talvez criando um contorno de cada cor para identificarmos fácil qual é qual.

O modelo atual tira os eventos internos e nem todos se tocam em trocar o filtro para ver o que tem.

**Comment by rafaeleyng** [comment]
Concordo.
Existe ainda mais uma categoria, mas que vai dar mais trabalho.
Farei tudo junto daqui há uns dias.

**Comment by Alexandre-Machado** [comment]
:+1:

**Comment by rafaeleyng** [comment]
Essa "mais uma categoria" que eu falei é a de pessoas da CWI palestrando em eventos.

**Comment by rafaeleyng** [comment]
Feito
