### ISSUE TITLE
Como suportar divulgação de call-for-papers?

### ISSUE THREAD

**Issue by rafaeleyng** [CWISoftware/eventos#29]

**Comment by brunotrassante** [comment]
Como call 4 papers costumaser uma "fase" do evento, nao mudando suas datas etc, acho que poderia ter tipo uma faixa em cima do card( estilo o fork me, mas maior) para destacar a fase. Colocando data de fim e link para o site ao clicar. Que tal?

**Comment by rafaeleyng** [comment]
Gostei

**Comment by rafaeleyng** [comment]
Eu criei a issue mas pensando mais a respeito acho que é melhor não ter isso. É uma coisa a mais para dar manutenção, no caso ficar atualizando o status do evento. Acho que a solução mais simples é, quando abrir o call for papers, simplesmente cadastrar o próprio evento.

**Comment by brunotrassante** [comment]
Concordo, podemos simplificar e vai atender.
