### ISSUE TITLE
Ordenamento dos eventos 

### ISSUE THREAD

**Issue by brunotrassante** [CWISoftware/eventos#31]
Talvez descorrente ao excesso de datas. Os eventos de 2016 estão aparecendo não com os mais próximos em cima

**Comment by rafaeleyng** [comment]
Eu havia implementado com ordenação por data, a data mais para a frente aparecendo em cima, independentemente de ser mais próximo ou não. O BrazilJS ali na verdade é uma forçação, porque eu coloquei ele só para ter algum evento para 2016, qualquer que fosse, apenas para aparecer o menu de anos. Normalmente não haveria um evento cadastrado que irá acontecer num futuro tão distante como esse.

Mas acho que posso tentar algo para melhorar isso.

Estou querendo mudar um pouco a stack de front-end desse site, aí essas mudanças ficarão mais fáceis de serem feitas. Só estou tendo que estudar um pouco antes de fazer.

**Comment by brunotrassante** [comment]
:+1:
Excelente!

**Comment by giordanowt** [comment]
A ordenação dos eventos foi corrigida e está funcionando da seguinte forma:

Está sendo ordenado da data mais próxima para mais distante, para os eventos que já ocorreram
e para os eventos que ocorrerão.
