### ISSUE TITLE
Bug quando é feito a seleção pela segunda vez nas opções externo/interno

### ISSUE THREAD

**Issue by Alexandre-Machado** [CWISoftware/eventos#39]
Quanto é feito pela segunda vez a seleção, a seleção do ano é perdida.

- Chrome 48
- Firefox 44.0.2

![screencast](https://cloud.githubusercontent.com/assets/1766903/13321651/1e10eb5a-dbaf-11e5-93c6-2c12f56fc7f0.gif)

**Comment by rafaeleyng** [comment]
Isso aí é bug relacionado ao React Router. Eu quis usar, mas não soube usar direito. O @brunotrassante falou algo em reverter para a versão que não usava o router. Teria que ver qual vai ser a decisão. Eu estava em viagem, não acompanhei mais nada nas últimas semanas.

**Comment by giordanowt** [comment]
Em uma conversa com o @brunotrassante, optamos por ocultar temporariamente esses caras da página.
