### ISSUE TITLE
Listagem de eventos passados

### ISSUE THREAD

**Issue by mkautzmann** [CWISoftware/eventos#54]
Olá.

Primeiro, parabéns pela iniciativa do projeto.

Notei pelo fonte e pela visualização da listagem no site que os eventos passados são jogados para o fim da lista.

A minha intuição de ordem por data se confunde quando chego num evento achando que ele está mais adiante no futuro e depois olho a data e vejo que ele já passou.

Acredito que deveria se ter uma indicação que esses eventos já passaram ou ainda um filtro que esconda esses eventos.

O que vocês acham?

**Comment by rafaeleyng** [comment]
Oi Matheus. 

Obrigado pela contribuição. Acho uma boa ideia. Sugiro que tu faça um pull request com a alteração, que eu reviso e aceito.

Abraço

**Comment by mkautzmann** [comment]
OK, já tinha subido primeiro a PR #55 para eventos em andamento.

**Comment by rafaeleyng** [comment]
Closed via #55
