### ISSUE TITLE
Otimizar os assets

### ISSUE THREAD

**Issue by rafaeleyng** [CWISoftware/eventos#6]
Provavelmente usando https://github.com/jekyll/jekyll-assets

**Comment by rafaeleyng** [comment]
O que eu fiz por enquanto é concatenar os JS. Acho que está bom, para começar.

**Comment by brunotrassante** [comment]
Nice! Boa escolha o jekyll/. O pessoal está acostumado com essa sintax para formatação

**Comment by rafaeleyng** [comment]
Otimizei CSS e HTML, o JS vendor já está minificado e o JS da aplicação vai ter que ficar aberto mesmo. Se minificasse a diferença seria de menos de 1kb, então azar.
